### ISSUE TITLE
Running tests containing Windows Service fail with the latest Puppet versions on Unix machines

### ISSUE THREAD

**Issue by franknarf8** [puppetlabs/rspec-puppet#14]
## Describe the Bug

When upgrading to the latest puppet (7.12.0, 6.25.0 and later; 7.11.0 and 6.24.0 are ok), test calling windows service start failing when they are run on Unix machines. 

The problem was introduced by this commit to the puppet repo : https://github.com/puppetlabs/puppet/commit/ab3870c90552a70041cf7115b1a81a01c86768c2
in `lib/puppet/type/service.rb`

The code is trying to access the constant of a module that was never imported/initialized.

## Expected Behavior

rspec-puppet should support the latest puppet version when in comes to windows services.

## Steps to Reproduce

Write a test for a class that uses a puppet service with the windows provider and run with one of the puppet version mentioned above.

## Environment
 - Puppet : 7.12.0
 - Platform : MacOS (Intel) (Also probably happening on other unix systems)

## Additional Context

Stacktrace : 
```
NameError: uninitialized constant Puppet::Util::Windows

  0) module::using:windows_service catalog compile for windows is expected to compile into a catalogue without dependency cycles
     Failure/Error: it { is_expected.to compile.with_all_deps }

     NameError:
       uninitialized constant Puppet::Util::Windows
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/puppet-7.12.0-universal-darwin/lib/puppet/provider/service/windows.rb:119:in `default_timeout'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/puppet-7.12.0-universal-darwin/lib/puppet/type/service.rb:275:in `block (3 levels) in <module:Puppet>'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/puppet-7.12.0-universal-darwin/lib/puppet/type.rb:844:in `set_default'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-puppet-2.7.10/lib/rspec-puppet/monkey_patches.rb:87:in `call'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-puppet-2.7.10/lib/rspec-puppet/monkey_patches.rb:87:in `block in <class:Type>'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/puppet-7.12.0-universal-darwin/lib/puppet/type.rb:2485:in `block in set_parameters'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/puppet-7.12.0-universal-darwin/lib/puppet/type.rb:2484:in `each'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/puppet-7.12.0-universal-darwin/lib/puppet/type.rb:2484:in `set_parameters'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/puppet-7.12.0-universal-darwin/lib/puppet/type.rb:2373:in `initialize'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/puppet-7.12.0-universal-darwin/lib/puppet/resource.rb:475:in `new'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/puppet-7.12.0-universal-darwin/lib/puppet/resource.rb:475:in `to_ral'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/puppet-7.12.0-universal-darwin/lib/puppet/resource/catalog.rb:610:in `block in to_catalog'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/puppet-7.12.0-universal-darwin/lib/puppet/resource/catalog.rb:602:in `each'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/puppet-7.12.0-universal-darwin/lib/puppet/resource/catalog.rb:602:in `to_catalog'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/puppet-7.12.0-universal-darwin/lib/puppet/resource/catalog.rb:495:in `to_ral'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-puppet-2.7.10/lib/rspec-puppet/matchers/compile.rb:149:in `cycles_found?'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-puppet-2.7.10/lib/rspec-puppet/matchers/compile.rb:25:in `matches?'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-expectations-3.10.1/lib/rspec/expectations/handler.rb:51:in `block in handle_matcher'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-expectations-3.10.1/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-expectations-3.10.1/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-expectations-3.10.1/lib/rspec/expectations/expectation_target.rb:65:in `to'
     # ./spec/classes/unit/profile/codesign_spec.rb:16:in `block (3 levels) in <top (required)>'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:262:in `instance_exec'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:262:in `block in run'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:508:in `block in with_around_and_singleton_context_hooks'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:465:in `block in with_around_example_hooks'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:486:in `block in run'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:624:in `run_around_example_hooks_for'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:486:in `run'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:465:in `with_around_example_hooks'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:508:in `with_around_and_singleton_context_hooks'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:259:in `run'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:644:in `block in run_examples'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:640:in `map'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:640:in `run_examples'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:606:in `run'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `block in run'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `map'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `run'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `map'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:2067:in `with_suite_hooks'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:74:in `report'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:115:in `run_specs'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:89:in `run'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:71:in `run'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:45:in `invoke'
     # /Users/user/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/exe/rspec:4:in `<top (required)>'
     # /Users/user/.rbenv/versions/2.7.4/bin/rspec:23:in `load'
     # /Users/user/.rbenv/versions/2.7.4/bin/rspec:23:in `<main>'
    is expected to compile into a catalogue without dependency cycles (FAILED - 1)
```
